### PR TITLE
fix(command-mode): fix shift key and capitalization behaviour

### LINKED ISSUE #287: Text entry is being capitalized for Scribe command bar
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Currently the text is being set to all caps for command bar text entry and the shift key isn't working to switch it back to lower case. See the video below for details:

[Screen_recording_20250102_002642.webm](https://github.com/user-attachments/assets/e78f68d3-fbab-4434-a578-0542324b369e)

Ideally the plural command would start out with capitalized words for German as all nouns are capitalized in German, and aside from that we want the keyboards current capitalization state to transfer into the command bar text entry. Beyond this, we also need to fix the shift key not changing it's icon to show that shift is enabled during command modes (it's pressed multiple times in the video above).

### Device type

Emulator is a Pixel 8 Pro

### Versions

Current development branch

### PR DESCRIPTION
**Pull request by smalik2811**
Correct capitalization behavior, fix shift key icon, and handle German plural noun capitalization.

Closes #287

### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

This pull request addresses issue #287 by resolving several issues with the command bar:

- **Corrected text capitalization behavior:** Ensured correct capitalization of text entered in the command bar, including proper handling of cases like German plural nouns.
- **Fixed shift key icon behavior:** Corrected an issue where the shift key icon and label of the keys did not accurately reflect the shift key state during command mode.

### Related issue

-   #287

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks for this, @smalik2811! :) We'll get to the review soon 😊

File: app/src/main/java/be/scri/services/GeneralKeyboardIME.kt [hunk 1]
```diff
@@ -336,6 +336,10 @@ abstract class GeneralKeyboardIME(
             Log.i("MY-TAG", "PLURAL STATE")
             updateKeyboardMode(true)
             currentState = ScribeState.PLURAL
+            if (language == "German") {
```
Comment (andrewtavis) [inline app/src/main/java/be/scri/services/GeneralKeyboardIME.kt:339]: Wonderful, thanks for this, @smalik2811!

**Comment by andrewtavis** [comment]
One thing to note here is that we should switch to the letter keys when the user selects a command, but we can work on this in another issue :)
