### PR TITLE
fix: Capitalize conjugations when input verb is capitalized

### LINKED ISSUE #523: Capitalize conjugations if the entered text is capitalized
### Terms

- [x] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Android/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [x] I agree to follow Scribe-Android's [Code of Conduct](https://github.com/scribe-org/Scribe-Android/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

In #512 we worked on inputs being able to be capitalized for Scribe commands. One thing that's needed to finalize this functionality is that the conjugations available to the user in a table should be capitalized if the word entered into the conjugate command is capitalized. An example where this is not the case is for the verb "to be" in Spanish (ser):

Image

Going through the capitalization for the commands:
- Translate: The returned word should be capitalized if the input is (German nouns always capitalized)
- Conjugate: The verb conjugations should be capitalized if the input is
- Plural: The returned noun should be capitalized if the input is (German plurals always capitalized)

### Device type

Phones and tablets

### Versions

The current version of main

### PR DESCRIPTION
**Pull request by junior-od**
### Contributor checklist

-   [x] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch
-   [x] I have tested my code with the `./gradlew lintKotlin detekt test` command as directed in the [testing section of the contributing guide](https://github.com/scribe-org/Scribe-Android/blob/main/CONTRIBUTING.md#testing)

---

### Description

This pull request fixes an issue where conjugation results did not respect the capitalization of the input verb.
Previously, when users entered a capitalized or all-caps verb (for example, Sein or HABEN), the generated conjugations were returned entirely in lowercase, which broke consistency with the user’s input and reduced readability. This change ensures that when a capitalized verb is provided, the conjugated forms are returned in a normalized title-case format (only the first letter of each form is capitalized).

### What was changed

1. handleConjugateState()

- Now detects whether the input verb is capitalized (title case or all caps).

2. applyCapitalizationToConjugations() (new helper)

- Transforms the conjugation output so that only the first character of each conjugated form is capitalized when needed.

3. handlePluralOrTranslateState()

- Enhanced handlePluralOrTranslateState() to detect and preserve ALL CAPS formatting

Conjugation map processing
Capitalization is now applied consistently to all conjugated forms in the result structure.

### Related issue

-   #ISSUE_NUMBER
     Closes #523

### CODE REVIEW

**Comment by andrewtavis** [comment]
Thanks so much for the PR and your interest in the project, @junior-od! We'll try to get to the review in the coming days :)

@delemike and/or @angrezichatterbox: Would either of you have a moment for an initial review? I'll also do a check maybe tomorrow night, but just in case either of you have time before :)

**Review by DeleMike — COMMENTED** [review]
Thanks for the PR @junior-od, please look into my comment to know what to adjust.

Thank you again for contributing :)

File: app/src/main/java/be/scri/services/GeneralKeyboardIME.kt [hunk 1]
```diff
@@ -2364,6 +2364,7 @@ abstract class GeneralKeyboardIME(
 
     /**
      * Handles the Enter key press when in the plural or translate state.
+     * Now supports ALL CAPS input formatting.
```
Comment (DeleMike) [inline app/src/main/java/be/scri/services/GeneralKeyboardIME.kt]: Thanks @junior-od! 
I do not think this is necessary.

File: app/src/main/java/be/scri/services/GeneralKeyboardIME.kt [hunk 2]
```diff
@@ -2400,6 +2419,7 @@ abstract class GeneralKeyboardIME(
     /**
      * Handles the Enter key press when in the `CONJUGATE` state. It fetches the
      * conjugation data for the entered verb and transitions to the selection view.
+     * Now supports ALL CAPS input formatting.
```
Comment (DeleMike) [inline app/src/main/java/be/scri/services/GeneralKeyboardIME.kt]: this too

Comment (andrewtavis) [reply app/src/main/java/be/scri/services/GeneralKeyboardIME.kt]: Similarly will remove :)

**Review by andrewtavis — APPROVED** [review]
praise: All's working really well here, @junior-od! Thanks for the great implementation here and for reacting to requests from reviewers 😊

praise: Thanks for the detailed first review here, @DeleMike!

Glad to have this finished :) Great work, all!
